included: # File Paths to be included
  - ProfileKit

excluded: # File Paths to be excluded


disabled_rules:
  #- block_based_kvo
  #- class_delegate_protocol
  #- closing_brace
  #- closure_parameter_position
  #- colon
  #- comma
  #- compiler_protocol_init
  #- control_statement
  #- custom_rules
  - cyclomatic_complexity
  #- discarded_notification_center_observer
  #- discouraged_direct_init
  #- dynamic_inline
  #- empty_enum_arguments
  #- empty_parameters
  #- empty_parentheses_with_trailing_closure
  #- fallthrough
  #- file_length
  #- for_where
  - force_cast
  #- force_try
  - function_body_length
  #- function_parameter_count
  #- generic_type_name
  - identifier_name
  #- implicit_getter
  #- is_disjoint
  #- large_tuple
  #- leading_whitespace
  #- legacy_cggeometry_functions
  #- legacy_constant
  #- legacy_constructor
  #- legacy_nsgeometry_functions  
  - line_length
  #- mark
  #- multiple_closures_with_trailing_closure
  #- nesting
  #- notification_center_detachment
  #- opening_brace
  #- operator_whitespace
  #- private_over_fileprivate
  #- private_unit_test
  #- protocol_property_accessors_order
  #- redundant_discardable_let
  #- redundant_optional_initialization
  #- redundant_string_enum_value
  #- redundant_void_return
  #- return_arrow_whitespace
  #- shorthand_operator
  #- statement_position
  #- superfluous_disable_command
  #- switch_case_alignment
  #- syntactic_sugar
  - todo
  #- trailing_comma
  #- trailing_newline
  #- trailing_semicolon
  #- trailing_whitespace  
  #- type_body_length
  #- type_name
  #- unneeded_break_in_switch
  #- unused_closure_parameter
  #- unused_enumerated
  #- unused_optional_binding
  #- valid_ibinspectable
  #- vertical_parameter_alignment
  #- vertical_whitespace
  #- void_return
  #- weak_delegate
  #- xctfail_message

opt_in_rules: # Optional Rules
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - nimble_operator
  #- number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  - xct_specific_matcher
  #- yoda_condition

file_header: # Correct syntax for the file headers
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Profiles
                    \/\/
                    \/\/  Created by .[A-Za-z -]*?\.
                    \/\/  Copyright © \d{4} .[A-Za-z -]*?\. All rights reserved\.
                    \/\/
